engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
  csslint:
    enabled: false
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
      import/no-unresolved:
        enabled: false
      no-console:
        enabled: false
      strict:
        enabled: false
      no-unused-vars:
        enabled: false
      no-undef:
        enabled: false
      class-methods-use-this:
        enabled: false
      no-param-reassign:
        enabled: false
      array-callback-return:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/InvertedIndex.js"
    - "spec/dplex-test-spec.js"
exclude_paths:
- "samples/*"
- "*.json"
- "src/app.js"
- "css/*"
- "index.html"
- "specs/*"
- .travis.yml
- .eslintrc.json
- .babelrc
