sudo: required
dist: trusty
language: node_js
node_js:
  - 6
before_script:
  - npm install
script:
  - npm test

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
after_script:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js